service: middlewares-middy
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  Account:
    handler: functions/Account/index.handler
    events:
      - httpApi:
          path: '/account'
          method: GET

resources:
  Resources:
    jwtAccounts:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: accounts
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
